[package]
name = "tracing-build-script-tests"
build = "build.rs"
edition = "2021"

[build-dependencies]
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
tracing-build-script = { path = "../tracing-build-script" }
