name: Cargo Test
on: push

jobs:
  cargo-test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - uses: actions/checkout@v4
      - name: Run Unittests
        run: |
          cargo test
